export const agentCatalog = [
  {
    id: 'main',
    name: '主控助手',
    role: '任务理解与调度',
    state: 'idle',
    task: '理解自然语言请求，拆解任务并选择合适的能力执行器。',
    supervisor: true,
    layout: { x: '50%', y: '45%', w: '30%', h: '21%', z: 7 },
    metric: '等待指令',
    label: '主控',
    accent: '#2563EB',
    darkAccent: '#1D4ED8',
    bubble: '调度',
    executor: 'supervisor',
  },
  {
    id: 'file-agent',
    name: '文件助手',
    role: '本地文件',
    state: 'idle',
    task: '建立本地文本索引，按文件名和内容检索资料，提取摘要和下一步建议。',
    layout: { x: '18%', y: '74%', w: '22%', h: '22%', z: 6 },
    metric: '可索引工作区文件',
    label: '文件',
    accent: '#0F766E',
    darkAccent: '#115E59',
    bubble: '索引',
    executor: 'file',
  },
  {
    id: 'research-agent',
    name: '研究助手',
    role: '联网检索与网页',
    state: 'idle',
    task: '统一处理联网问答、网页读取、搜索结果整理和轻量浏览器操作。',
    layout: { x: '43%', y: '78%', w: '22%', h: '20%', z: 4 },
    metric: '可搜索与读网页',
    label: '研究',
    accent: '#7C3AED',
    darkAccent: '#6D28D9',
    bubble: '检索',
    executor: 'gemini-search',
  },
  {
    id: 'writing-agent',
    name: '文书助手',
    role: '文字材料撰写',
    state: 'idle',
    task: '撰写、改写、总结文字材料，并可从录音转写生成纪要。',
    layout: { x: '62%', y: '76%', w: '22%', h: '20%', z: 4 },
    metric: '可撰写材料',
    label: '文书',
    accent: '#16A34A',
    darkAccent: '#15803D',
    bubble: '撰写',
    executor: 'writing',
  },
  {
    id: 'schedule-agent',
    name: '日程助手',
    role: '日程管理',
    state: 'reserved',
    task: '预留日程、提醒、排期和日历协同能力，当前先不执行具体动作。',
    layout: { x: '72%', y: '62%', w: '19%', h: '18%', z: 3 },
    metric: '能力预留',
    label: '日程',
    accent: '#0EA5E9',
    darkAccent: '#0284C7',
    bubble: '预留',
    executor: 'schedule',
  },
  {
    id: 'app-agent',
    name: '应用助手',
    role: '系统与应用',
    state: 'idle',
    task: '启动应用、准备草稿、执行系统动作。敏感操作必须二次确认。',
    layout: { x: '86%', y: '76%', w: '20%', h: '20%', z: 3 },
    metric: '待接入本机应用',
    label: '应用',
    accent: '#DC2626',
    darkAccent: '#B91C1C',
    bubble: '确认',
    executor: 'system',
  },
]

export const demoTask = '帮我看看这个项目现在有哪些文件，并给出下一步改造建议'
