export const agentCatalog = [
  {
    id: 'main',
    name: '主控助手',
    role: '任务理解与调度',
    state: 'idle',
    task: '理解自然语言请求，拆解任务并选择合适的能力执行器。',
    supervisor: true,
    layout: { x: '50%', y: '45%', w: '30%', h: '21%', z: 7 },
    metric: '等待指令',
    label: '主控',
    accent: '#2563EB',
    darkAccent: '#1D4ED8',
    bubble: '调度',
    executor: 'supervisor',
  },
  {
    id: 'file-agent',
    name: 'Claude 文件员',
    role: 'Claude 桌面 Agent · 本地文件',
    state: 'idle',
    task: '建立本地文本索引，按文件名和内容检索资料，提取摘要和下一步建议。',
    layout: { x: '18%', y: '76%', w: '22%', h: '20%', z: 6 },
    metric: '可索引工作区文件',
    label: '文件',
    accent: '#D97757',
    darkAccent: '#AF5A41',
    bubble: 'Claude',
    executor: 'file',
    persona: 'claude-desktop',
  },
  // 底排四个吉祥物统一 y=76% / h=20%，让脚底基线对齐。
  {
    id: 'research-agent',
    name: 'Codex 研究宠物',
    role: 'Codex 宠物 Agent · 联网检索与网页',
    state: 'idle',
    task: '统一处理联网问答、网页读取、搜索结果整理和轻量浏览器操作。',
    layout: { x: '43%', y: '76%', w: '22%', h: '20%', z: 4 },
    metric: '可搜索与读网页',
    label: '研究',
    accent: '#5B8CFF',
    darkAccent: '#3367D6',
    bubble: 'Codex',
    executor: 'gemini-search',
    persona: 'codex-pet',
  },
  {
    id: 'writing-agent',
    name: '企鹅文书员',
    role: '企鹅 Agent · 文字材料撰写',
    state: 'idle',
    task: '撰写、改写、总结文字材料，并可从录音转写生成纪要。',
    layout: { x: '62%', y: '76%', w: '22%', h: '20%', z: 4 },
    metric: '可撰写材料',
    label: '文书',
    accent: '#EF4444',
    darkAccent: '#111827',
    bubble: '文书',
    executor: 'writing',
    persona: 'penguin',
  },
  {
    id: 'schedule-agent',
    name: '小度日程机器人',
    role: '小度机器人 Agent · 日程管理',
    state: 'reserved',
    task: '预留日程、提醒、排期和日历协同能力，当前先不执行具体动作。',
    layout: { x: '72%', y: '62%', w: '19%', h: '18%', z: 3 },
    metric: '能力预留',
    label: '日程',
    accent: '#58B7FF',
    darkAccent: '#1E3A8A',
    bubble: '小度',
    executor: 'schedule',
    persona: 'xiaodu-robot',
  },
  {
    id: 'app-agent',
    name: '红球应用伙伴',
    role: '红球 Agent · 系统与应用',
    state: 'idle',
    task: '启动应用、准备草稿、执行系统动作。敏感操作必须二次确认。',
    layout: { x: '86%', y: '76%', w: '20%', h: '20%', z: 3 },
    metric: '待接入本机应用',
    label: '应用',
    accent: '#EF4444',
    darkAccent: '#991B1B',
    bubble: '确认',
    executor: 'system',
    persona: 'red-orb',
  },
]

export const demoTask = '帮我看看这个项目现在有哪些文件，并给出下一步改造建议'
